### ISSUE TITLE
support rxi/log.lua

### ISSUE THREAD

**Issue by SiENcE** [rxi/lovebird#5]
What about adding support for your rxi/log.lua coloring?

**Comment by rxi** [comment]
If you wanted to add this yourself the easiest way to go about it would probably be to wrap `lovebird.print()` (or override it) and replace the ANSI color escape codes with the corresponding HTML tags for coloring the text before passing it to the original `lovebird.print()` function (also making sure to set `lovebird.allowhtml` to true). Even easier still might be to modify *log.lua* to use HTML instead of ANSI color codes.

I didn't have plans to do this and I likely won't accept such changes into either project. It seems out of the scope of *log.lua* and *log.lua* doesn't seem like it would be used by enough people to make it worth changing *lovebird* for.

That being said if you decide to make the changes I mention above for your own project and get stuck let me know, I'd be happy to answer questions.

**Comment by SiENcE** [comment]
Sorry for late reply.

Thanks for help and your suggestion to just overwrite lovebird.print()!
